// =============================================
// Detector de género por nombre
// Basado en nombres comunes peruanos/latinos
// =============================================

const NOMBRES_MASCULINOS = new Set([
  'ABEL','ABELARDO','ABRAHAM','ADAN','ADRIAN','AGUSTIN','ALAN','ALBERTO','ALDO','ALEJANDRO',
  'ALEX','ALEXANDER','ALEXIS','ALFONSO','ALFREDO','ALONSO','ALVARO','AMILCAR','ANDERSON','ANDRES',
  'ANGEL','ANIBAL','ANTHONY','ANTONIO','AQUILES','ARMANDO','ARNALDO','ARTURO','AUGUSTO',
  'BARTOLOME','BASILIO','BENITO','BENJAMIN','BERNARDO','BORIS','BRAULIO','BRAYAN','BRIAN','BRUNO',
  'CALEB','CAMILO','CARLOS','CARMELO','CESAR','CHRISTIAN','CHRISTOPHER','CLAUDIO','CLEMENTE','CRISTHIAN','CRISTIAN','CRISTOBAL',
  'DAGOBERTO','DANIEL','DANTE','DARIO','DAVID','DELFIN','DEMETRIO','DENIS','DENNIS','DIEGO','DIMAS','DOMINGO','DONATO',
  'EDDY','EDEN','EDGAR','EDGARDO','EDISON','EDMUNDO','EDUARDO','EDWIN','EFRAIN','ELIAS','ELMER','ELVIS','EMERSON','EMILIO','ENRIQUE','ERACLEO','ERASMO','ERIC','ERICK','ERNESTO','ERWIN','ESTEBAN','EUGENIO','EUSEBIO','EZEQUIEL',
  'FABIAN','FABRICIO','FAUSTO','FEDERICO','FELIPE','FELIX','FERNANDO','FIDEL','FILOMENO','FLAVIO','FLORENCIO','FRANCISCO','FRANCO','FRANK','FRANKLIN','FREDDY','FREDY',
  'GABRIEL','GAEL','GENARO','GEORGE','GERALDO','GERARDO','GERMAN','GERSON','GILBERTO','GINO','GIOVANNI','GONZALO','GREGORIO','GUILLERMO','GUSTAVO',
  'HANS','HAROLD','HECTOR','HENRY','HERNAN','HERNANDO','HILARIO','HIPOLITO','HOMERO','HORACIO','HUBER','HUBERTO','HUGO','HUMBERTO',
  'IGNACIO','IKER','IRVIN','ISAAC','ISAIAS','ISMAEL','ISRAEL','IVAN',
  'JACINTO','JACKSON','JACOB','JAIME','JAMES','JAMPIER','JAVIER','JEAN','JEFFERSON','JEREMY','JESUS','JHON','JHONATAN','JIMMY','JOAN','JOAQUIN','JOEL','JOHAN','JOHN','JONATHAN','JORDAN','JORGE','JOSE','JOSUE','JUAN','JULIO','JUNIOR','JUSTO',
  'KEVIN','KURT',
  'LAZARO','LEANDRO','LEONARDO','LEONEL','LEOPOLDO','LESTER','LINCOLN','LUCIANO','LUCIO','LUIS','LUTHER',
  'MANUEL','MARCELO','MARCIAL','MARCO','MARCOS','MARIANO','MARIO','MARTIN','MATEO','MATIAS','MAURICIO','MAX','MAXIMO','MICHAEL','MIGUEL','MOISES',
  'NAPOLEON','NATALIO','NATIVIDAD','NELSON','NESTOR','NICOLAS','NOEL','NOLBERTO',
  'OCTAVIO','OLIVER','OMAR','ORLANDO','OSCAR','OSVALDO','OVIDIO',
  'PABLO','PANTALEON','PASCUAL','PATRICIO','PAUL','PEDRO','PERCY','PETER','PIERRE','PIO',
  'RAFAEL','RAIDEN','RAIMUNDO','RAMIRO','RAMON','RAUL','RAYNER','RENZO','RENATO','RENE','REYES','REYNALDO','RICARDO','RICHARD','RIGOBERTO','ROBERT','ROBERTO','RODRIGO','ROGELIO','ROGER','ROLANDO','ROMAN','RONALD','RONALDO','ROQUE','RUBEN','RUDY','RUFINO',
  'SALVADOR','SAMUEL','SANTIAGO','SANTOS','SAUL','SEBASTIAN','SEGUNDO','SERGIO','SILVESTRE','SILVIO','SIMON','SIXTO','SMITH',
  'TEODORO','TOMAS','TONY',
  'ULISES','URBANO',
  'VALENTIN','VICTOR','VICENTE','VIRGILIO','VLADIMIR',
  'WALTER','WASHINGTON','WILDER','WILFREDO','WILLIAM','WILLY','WILSON',
  'YAIR','YOEL','YORDAN',
  'ZENON',
]);

const NOMBRES_FEMENINOS = new Set([
  'ABIGAIL','ADELA','ADELAIDA','ADRIANA','AGUSTINA','AIDE','AIMEE','ALBA','ALEJANDRA','ALEXANDRA','ALICIA','ALINA','ALLISON','ALMA','AMALIA','AMANDA','AMELIA','AMPARO','ANA','ANABEL','ANAHI','ANDREA','ANGELA','ANGELICA','ANGELINA','ANGIE','ANITA','ANTONIA','ARACELI','ARIANA','ASTRID','AURORA','AYLIN',
  'BARBARA','BEATRIZ','BELEN','BERENICE','BERTHA','BIANCA','BLANCA','BRENDA','BRIGITTE','BRUNELLA',
  'CAMILA','CANDIDA','CARLA','CARLOTA','CARMEN','CAROLINA','CATALINA','CECILIA','CELIA','CELESTE','CINTHIA','CINTHYA','CLARA','CLAUDIA','CLOTILDE','CONSUELO','CORINA','CRISTINA',
  'DAFNE','DALIA','DANIELA','DELIA','DENISSE','DIANA','DINA','DOLORES','DOMINGA','DORIS','DULCE',
  'EDITH','ELENA','ELIANA','ELISA','ELIZABETH','ELOISA','ELSA','ELVIRA','EMILIA','EMILY','EMMA','ENMA','ERIKA','ESMERALDA','ESPERANZA','ESTEFANIA','ESTELA','ESTHER','ESTRELLA','EUGENIA','EVA','EVANGELINA','EVELYN',
  'FABIOLA','FATIMA','FELICITA','FERNANDA','FIDELA','FILOMENA','FIORELLA','FLOR','FLORA','FLORENCIA','FRANCISCA',
  'GABRIELA','GENESIS','GENOVEVA','GEORGINA','GERALDINE','GIANELLA','GINA','GISEL','GISELA','GISELLA','GLADYS','GLORIA','GRACE','GRACIELA','GRISELDA','GUADALUPE',
  'HAYDEE','HERLINDA','HERMINIA','HILARIA','HILDA',
  'INES','INGRID','IRENE','IRIS','IRMA','ISABEL','IVANA','IVETTE','IVONNE',
  'JACQUELINE','JANET','JANETH','JAQUELINE','JAZMIN','JENNIFER','JESSICA','JIMENA','JOHANA','JORGINA','JOSEFA','JOSEFINA','JUANA','JUDITH','JULIA','JULIANA','JULISSA','JUSTINA',
  'KAREN','KARINA','KARLA','KATHERINE','KATIA','KEIKO','KELLY','KIMBERLY',
  'LARA','LAURA','LEONOR','LETICIA','LIDIA','LILIA','LILIANA','LINA','LINDA','LIZETH','LORENA','LOURDES','LUCIA','LUCILA','LUCINDA','LUCRECIA','LUISA','LUZ',
  'MABEL','MACARENA','MAGALI','MAGALY','MAGDALENA','MAIRA','MANUELA','MARCELA','MARCIA','MARGARITA','MARIA','MARIANA','MARIELA','MARIELLA','MARILUZ','MARINA','MARISOL','MARITZA','MARLENE','MARTA','MARTHA','MATILDE','MAURA','MAXIMA','MELISSA','MERCEDES','MICAELA','MILAGROS','MILDRED','MIRELLA','MIRIAM','MIRIAN','MONICA','MYRIAM',
  'NADIA','NANCY','NATALIA','NATALY','NATHALY','NATIVIDAD','NELLY','NICOLE','NIDIA','NILDA','NILDA','NOELIA','NOEMI','NORA','NORMA','NURIA',
  'OFELIA','OLGA','OLINDA','OLIVIA',
  'PAMELA','PAOLA','PATRICIA','PAULINA','PERLA','PETRONA','PILAR','PRISCILA','PRISCILLA',
  'RAQUEL','REBECA','REGINA','REINA','RENATA','ROCIO','ROSA','ROSALIA','ROSALINA','ROSARIO','ROSEMARY','ROXANA','RUTH',
  'SABRINA','SALOME','SANDRA','SARA','SARAI','SELENE','SHIRLEY','SILVIA','SILVINA','SIMONA','SOFIA','SOLEDAD','SONIA','SORAYA','STEFANIA','STEPHANIE','SUSAN','SUSANA',
  'TAMARA','TANIA','TATIANA','TERESA','THALIA',
  'URSULA',
  'VALENTINA','VALERIA','VANESSA','VERONICA','VICTORIA','VILMA','VIOLETA','VIRGINIA','VIVIANA',
  'WENDY','WILDA',
  'XIMENA','XIOMARA',
  'YADIRA','YAJAIRA','YANETH','YARITZA','YASMIN','YESENIA','YESSICA','YOLANDA','YULIANA','YURI',
  'ZOILA','ZULEMA','ZULMA',
]);

/**
 * Detecta el género probable basándose en el primer nombre.
 * @param {string} nombres - Nombres completos (puede tener 2 nombres)
 * @returns {'M'|'F'|''} - 'M' masculino, 'F' femenino, '' no determinado
 */
export function detectarGenero(nombres) {
  if (!nombres || typeof nombres !== 'string') return '';

  // Tomar solo el primer nombre y normalizarlo
  const primerNombre = nombres.trim().toUpperCase().split(/\s+/)[0];

  if (!primerNombre) return '';

  // Buscar coincidencia exacta
  if (NOMBRES_MASCULINOS.has(primerNombre)) return 'M';
  if (NOMBRES_FEMENINOS.has(primerNombre)) return 'F';

  // Heurísticas por terminación (común en español)
  // Nombres que terminan en 'A' suelen ser femeninos (excepciones: Ezra, Joshua, etc.)
  // Nombres que terminan en 'O' suelen ser masculinos
  if (primerNombre.endsWith('A') && !['JOSUA','EZRA','BORJA'].includes(primerNombre)) return 'F';
  if (primerNombre.endsWith('O')) return 'M';

  return '';
}
